# baseURL = 'https://steverohrlack.github.io/pages-hugo-test/'
languageCode = 'de-DE'
title = 'IG Spur1-Mitteldeutschland'
theme = 'ananke'

[params]
  custom_css = ["custom.css"]
  recent_posts_number = 999
  date_format = "Mon, 02 Jan 2006 15:04"

[params.spur0]
  motto = 'Informationen und Neuigkeiten der Spur1-Freunde aus Naumburg'
  logo_text = 'IG Spur1-Mitteldeutschland'

[params.ananke]
  show_recent_posts = true

[menu]
  [[menu.main]]
    identifier = "index"
    name = "Startseite"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "ueber"
    name = "Über"
    url = "/ueber"
    weight = 20
  [[menu.main]]
    identifier = "datenschutz"
    name = "Datenschutz"
    url = "/datenschutz"
    weight = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'
